### PR TITLE
Bugfixes/ES-433

### PR DESCRIPTION
**Pull request by Qeas**

### CODE REVIEW

**Review by EvgeniiIvanov — APPROVED** [review]
LGTM

**Comment by EvgeniiIvanov** [comment]
e2e tests:
--- PASS: TestDriver_deploy (968.49s)
    --- PASS: TestDriver_deploy/install_driver (31.49s)
    --- PASS: TestDriver_deploy/deploy_nginx_pod_with_dynamic_block_volume_provisioning (122.64s)
    --- PASS: TestDriver_deploy/deploy_nginx_pod_with_persistent_volume (120.56s)
    --- PASS: TestDriver_deploy/restore_snapshot_as_dynamically_provisioned_volume (236.69s)
    --- PASS: TestDriver_deploy/volume_cloning_check (124.75s)
    --- PASS: TestDriver_deploy/deploy_nginx_pod_in_diffenrent_k8s_zones (278.79s)
    --- PASS: TestDriver_deploy/uninstall_driver (22.05s)
PASS
ok  	command-line-arguments	968.496s
--------------------------------------------------------------------------------------------------------
Also sanity tests:
Summarizing 1 Failure:

[Fail] Node Service [It] should work 
/go/src/github.com/kubernetes-csi/csi-test/pkg/sanity/node.go:740

Ran 57 of 72 Specs in 177.758 seconds
FAIL! -- 56 Passed | 1 Failed | 0 Pending | 15 Skipped
--- FAIL: TestSanity (177.77s)
FAIL
Makefile:130: recipe for target 'test-csi-sanity-container' failed
make: *** [test-csi-sanity-container] Error 1
--------------------------------------------------------------------------------------------------------
And about volume expand. After modify pvc for dynamic volume (increase from 4Gi to 6Gi) I can see that it works on Nexenta side:
CLI@ns502-28> volume list 
 PATH                                                              VOLSIZE  USED   AVAIL   REFER  BLKSIZE
 pool1/csiVolumeGroup/nginx-existing                               1G       1.01G  10.53T  43K    32K
 pool1/csiVolumeGroup/pvc-ns-34c12e87-43df-49e4-b00a-5f30acdae95a  4G       4.03G  10.53T  54K    32K
 pool1/vg/vol1                                                     1G       1.01G  10.53T  12K    32K
CLI@ns502-28> 
CLI@ns502-28> 
CLI@ns502-28> volume list
 PATH                                                              VOLSIZE  USED   AVAIL   REFER  BLKSIZE
 pool1/csiVolumeGroup/nginx-existing                               1G       1.01G  10.53T  43K    32K
 pool1/csiVolumeGroup/pvc-ns-34c12e87-43df-49e4-b00a-5f30acdae95a  6G       6.05G  10.53T  54K    32K
 pool1/vg/vol1                                                     1G       1.01G  10.53T  12K    32K

**Comment by Qeas** [comment]
All tests succeeded with last commit:

Ran 57 of 72 Specs in 279.953 seconds
SUCCESS! -- 57 Passed | 0 Failed | 0 Pending | 15 Skipped
PASS

**Review by goldranjith — APPROVED** [review]
LGTM

**Pull request merged**
